# ----------------------------------------------------------------------------------------
#  AYUDA: Ayuda del programa
#  Autor: SteveCarpio-2025
# ----------------------------------------------------------------------------------------

import cfg.PDF_variables as sTv
from   cfg.PDF_librerias import *

# ----------------------------------------------------------------------------------------
#                                  CUADRO DE AYUDA
# ----------------------------------------------------------------------------------------
def sTv_ayuda():
    os.system("cls")
    print(Fore.MAGENTA + "=" * 96)
    print(Fore.MAGENTA + "                               Proceso PDF Lector\n")
    print(Fore.MAGENTA + " Este programa ha sido desarrollado en Python y utiliza ")
    print(Fore.MAGENTA + " ............... ")
    print(Fore.MAGENTA + " ................\n")
    print(Fore.MAGENTA + " ............... ")
    print(Fore.MAGENTA + "=" * 96)
    print("")
    print(Fore.WHITE + "Servidor:")
    print(Fore.WHITE + "    IP: 10.10.30.55 (Python)")
    print(Fore.WHITE + "    Usuario: Fiduciario")
    print(Fore.WHITE + "    Contraseña: Gestionada por Cerberus")
    print("")
    print(Fore.WHITE + "Ruta raíz:")
    print(Fore.WHITE + "    C:\\MisCompilados\\PROY_PDF_LECTOR\\")
    print("")
    print(Fore.WHITE + "Ejecución:")
    print(Fore.WHITE + "    PDF_LECTOR_Main.exe ")
    print("")
    print(Fore.WHITE + "Parámetros [? | PRO | DEV] (opcional):")
    print(Fore.WHITE + "    [vació]: Muestra el menú actual y se procesa en modo DEV")
    print(Fore.WHITE + "    ?: Muestra la ayuda del programa")
    print(Fore.WHITE + "    PRO: Se procesará todos los emisores que estén activos en la CNBV")
    print(Fore.WHITE + "    DEV: Se procesará solo 10 emisores para hacer una previsualización")
    print("")
    print(Fore.WHITE + "Planificación:")
    print(Fore.WHITE + "    Su ejecución será AD-DOC solicitada por el usuario")
    print("")
    print(Fore.WHITE + "Pasos de ejecución:")
    print("")
    print(Fore.YELLOW + "    1) .............")
    print(Fore.WHITE + "        Este paso ..........")
    print(Fore.WHITE + "        ....................")
    print("")
    print(Fore.GREEN + "    2) .............")
    print(Fore.WHITE + "        .............")
    print(Fore.WHITE + "        .................")
    print("")
    print(Fore.YELLOW + "    3) .................")
    print(Fore.WHITE + "        Este paso usará el informe DATOS que tiene la línea curl para hacer una descarga")
    print(Fore.WHITE + "        del tipo de fichero seleccionado 'excel o pdf' ")
    print("")
    print(Fore.BLUE + "    4) ...............")
    print(Fore.WHITE + "        Este paso extraerá la información de Estados Financieros de todos los excel ")
    print(Fore.WHITE + "        que se han descargado, filtrando por las hojas y filas definidas por el usuario")
    print("")
    print(Fore.BLUE + "    5) ..................")
    print(Fore.WHITE + "        Este paso creará un informe FINAL con los datos de los resúmenes creados ordenados")
    print(Fore.WHITE + "        y diferenciados por hojas independientes ")
    print(Fore.WHITE + "        * Se añade la creación de cuadros de resumen que no están terminados ")
    print("")
    print(Fore.YELLOW + "    6) ...................... ")
    print(Fore.WHITE + "        Este paso mandará vía email el informe FINAL a REPCOMUN")
    print(Fore.WHITE + "        adjunto se mandará el excel con los EEFF y una tabla descriptiva en el cuerpo del email ")
    print("")
    print(Fore.WHITE + "Dependencias importantes:")
    print("")
    print(Fore.WHITE + "    - Google Chrome:")
    print(Fore.WHITE + "        Es fundamental tener instalada una versión estable (no Beta).")
    print("")
    print(Fore.WHITE + "    - ChromeDriver:")
    print(Fore.WHITE + "        Debe coincidir con la versión de Google Chrome instalada.")
    print(Fore.WHITE + "        Ruta del binario: C:\\MisCompilados\\cfg\\chromedriver-win32\\chromedriver.exe")
    print(Fore.WHITE + "        Para otras versiones: C:\\MisCompilados\\cfg\\chromedriver-win32\\1??\\")
    print("")
    print(Fore.WHITE + "    - Acceso a las URL:")
    print(Fore.WHITE + "        https://xbrl.cnbv.gob.mx/visorXbrl.html#/enviosInformacionFinanciera")
    print("")
    print(Fore.WHITE + "    - Acceso SMTP de TDA:")
    print(Fore.WHITE + "        Se debe tener acceso a: zimbra.tda-sgft.com por el puerto 25 ")
    print("")

    print(Fore.MAGENTA + "=" * 94)
    print(Fore.WHITE + "  Para más ayuda, contactar con: SteveCarpio 'carpios@tda-sgft.com' (stv.madrid@gmail.com) ")
    print(Fore.WHITE + "  Versión 3 - 2025")
    print(Fore.MAGENTA + "=" * 94)